[package]
name = "anyrender_vello"
description = "Vello backend for anyrender"
version = "0.0.0"
homepage = "https://github.com/dioxuslabs/blitz"
repository = "https://github.com/dioxuslabs/blitz"
documentation = "https://docs.rs/anyrender_vello"
license.workspace = true
edition = "2024"
publish = false

[dependencies]
kurbo = { workspace = true }
peniko = { workspace = true }
vello = { workspace = true }
anyrender = { path = "../anyrender"}